### ISSUE TITLE
mac, Strongbox 3.0.0 wont open on Mac OS Catalina 10.15.7

### ISSUE THREAD

**Issue by seathasky** [ogri-la/strongbox#199]
![Screen Shot 2020-10-18 at 2 27 02 PM](https://user-images.githubusercontent.com/17598024/96376653-42287100-114e-11eb-8f2b-fe36feff3b78.png)

Not much else to say about this. Just wont open.

**Comment by seathasky** [comment]
![Screen Shot 2020-10-18 at 2 31 00 PM](https://user-images.githubusercontent.com/17598024/96376719-a3504480-114e-11eb-927d-f152494177f8.png)
Console message

**Comment by seathasky** [comment]
New info. Went to console and in system.log its reads:

Oct 18 16:03:08 Matthews-iMac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.java.88832): Failed to bootstrap path: path = /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java, error = 2: No such file or directory

Yet I do not have this issue with 2.0.0

**Comment by seathasky** [comment]
missing tilde from argument??

**Comment by seathasky** [comment]
I'm using https://github.com/jliddev/WowUp in the meanwhile, their app just went into Alpha for Mac users. I'll leave this open for other mac users, most likely wont respond though as i'll be making the switch. Thanks Devs of Strongbox!

**Comment by torkus** [comment]
It looks like a security setting with your OS but my mac test didn't involve running the jar so I'll double check this tonight.

> I'm using https://github.com/jliddev/WowUp in the meanwhile, their app just went into Alpha for Mac users. 

You might want to checkout [instawow](https://github.com/layday/instawow). It has a standalone executable now and the author develops primarily for macOS so support isn't second-class like you would get with WowUp or strongbox. instawow has also been around a long time and is quite stable with more sophisticated features.

If you're willing to mess with java and npm, you may be interested in these [other macOS clients](https://ogri-la.github.io/wow-addon-managers/?preset/name=unfiltered&field/feature-curseforge=&field/maintained=yes&field/software-licence=&field/windows=&field/eula=&field/feature-tukui=&field/ads=&field/source-available=&field/feature-wowinterface=&field/ui=&field/language=&field/feature-vcs-addons=&field/retail=yes&field/linux=&field/f-oss=yes&field/classic=yes&field/mac=yes*&field/feature-catalog-search=).

> I'll leave this open for other mac users, most likely wont respond though as i'll be making the switch. Thanks Devs of Strongbox!

'dev', singular. It's just me. Thank you for opening a ticket, fairweather friend.

**Comment by seathasky** [comment]
Honestly I love strongbox, it's probably the best out there. My only gripe
is that it's java based and not a standalone app on Mac, I can't even put
it on my dock. I know that may sound petty, I just honestly like to keep a
clean desktop. I do think you guys make a killer add-on installer though.
It's simple minimal and I love it more than most flashy things. The
non-apple app thing is literally my only gripe

**Comment by layday** [comment]
I am not able to run the JAR from the release either.  However I checked out `3.0.0` from the repo, bootstrapped Clojure and all the rest and ran `lein uberjar` and was able to open the JAR it produced without any problems.  I can see that on Travis strongbox is built under OpenJDK 14 but macOS comes (?) with version 13 - would that be causing issues?

**Comment by layday** [comment]
Okay, I tried the release JAR with OpenJDK 14 and that didn't work either. This is what I'm seeing:

```
❯ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment Zulu14.28+21-CA (build 14.0.1+8)
OpenJDK 64-Bit Server VM Zulu14.28+21-CA (build 14.0.1+8, mixed mode, sharing)
~/Downloads
❯ java -jar strongbox-3.0.0-standalone.jar
WARNING: cat already refers to: #'clojure.core/cat in namespace: net.cgrand.parsley.fold, being replaced by: #'net.cgrand.parsley.fold/cat
2020-10-19 03:32:22.328 java[21987:1502773] unable to obtain configuration from file:///Library/Preferences/com.apple.ViewBridge.plist due to Error Domain=NSCocoaErrorDomain Code=260 "The file “com.apple.ViewBridge.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Library/Preferences/com.apple.ViewBridge.plist, NSUnderlyingError=0x7fb415eac6c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2020-10-19 00:32:23.928 layday INFO [strongbox.core:1190] - starting app
2020-10-19 00:32:24.196 layday INFO [strongbox.core:839] - pruning http cache
2020-10-19 00:32:24.240 layday INFO [strongbox.utils:26] - instrumentation is OFF
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at javafx.application.Platform.startup(Platform.java:103)
        at cljfx.jdk.platform$initialize.invokeStatic(platform.clj:6)
        at cljfx.jdk.platform$initialize.invoke(platform.clj:4)
        at cljfx.platform$initialize.invokeStatic(platform.clj:30)
        at cljfx.platform$initialize.invoke(platform.clj:29)
        at cljfx.api$fn__22336.invokeStatic(api.clj:83)
        at cljfx.api$fn__22336.invoke(api.clj:70)
        at cljfx.api__init.load(Unknown Source)
        at cljfx.api__init.<clinit>(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:427)
        at clojure.lang.RT.classForName(RT.java:2211)
        at clojure.lang.RT.classForName(RT.java:2220)
        at clojure.lang.RT.loadClassForName(RT.java:2239)
        at clojure.lang.RT.load(RT.java:449)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6839.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$load_one.invoke(core.clj:5903)
        at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
        at clojure.core$load_lib.invokeStatic(core.clj:5947)
        at clojure.core$load_lib.doInvoke(core.clj:5928)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$load_libs.invokeStatic(core.clj:5989)
        at clojure.core$load_libs.doInvoke(core.clj:5969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$require.invokeStatic(core.clj:6007)
        at clojure.core$require.doInvoke(core.clj:6007)
        at clojure.lang.RestFn.invoke(RestFn.java:1096)
        at strongbox.ui.jfx$loading__6721__auto____20876.invoke(jfx.clj:1)
        at strongbox.ui.jfx__init.load(Unknown Source)
        at strongbox.ui.jfx__init.<clinit>(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:427)
        at clojure.lang.RT.classForName(RT.java:2211)
        at clojure.lang.RT.classForName(RT.java:2220)
        at clojure.lang.RT.loadClassForName(RT.java:2239)
        at clojure.lang.RT.load(RT.java:449)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6839.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$load_one.invoke(core.clj:5903)
        at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
        at clojure.core$load_lib.invokeStatic(core.clj:5947)
        at clojure.core$load_lib.doInvoke(core.clj:5928)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$load_libs.invokeStatic(core.clj:5985)
        at clojure.core$load_libs.doInvoke(core.clj:5969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$require.invokeStatic(core.clj:6007)
        at clojure.core$require.doInvoke(core.clj:6007)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at strongbox.main$jfx.invokeStatic(main.clj:57)
        at strongbox.main$jfx.invoke(main.clj:51)
        at strongbox.main$start.invokeStatic(main.clj:87)
        at strongbox.main$start.doInvoke(main.clj:79)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at strongbox.main$_main.invokeStatic(main.clj:222)
        at strongbox.main$_main.doInvoke(main.clj:216)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at strongbox.main.main(Unknown Source)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-10-19 00:32:24.505 layday ERROR [strongbox.main:26] - Uncaught exception on main
                            strongbox.main.main
                                            ...
                           strongbox.main/-main           main.clj:  216
                           strongbox.main/-main           main.clj:  222
                                            ...
                           strongbox.main/start           main.clj:   79
                           strongbox.main/start           main.clj:   87
                             strongbox.main/jfx           main.clj:   57
                                            ...
                           clojure.core/require           core.clj: 6007 (repeats 2 times)
                             clojure.core/apply           core.clj:  667
                                            ...
                         clojure.core/load-libs           core.clj: 5969
                         clojure.core/load-libs           core.clj: 5985
                             clojure.core/apply           core.clj:  667
                                            ...
                          clojure.core/load-lib           core.clj: 5928
                          clojure.core/load-lib           core.clj: 5947
                       clojure.core/load-lib/fn           core.clj: 5948
                          clojure.core/load-one           core.clj: 5908
                                            ...
                              clojure.core/load           core.clj: 6109
                              clojure.core/load           core.clj: 6125
                           clojure.core/load/fn           core.clj: 6126
                                            ...
                        java.lang.Class.forName         Class.java:  427
                       java.lang.Class.forName0          Class.java
                strongbox.ui.jfx__init.<clinit>
                    strongbox.ui.jfx__init.load                   :    1
               strongbox.ui.jfx/loading--auto--            jfx.clj:    1
                                            ...
                           clojure.core/require           core.clj: 6007 (repeats 2 times)
                             clojure.core/apply           core.clj:  667
                                            ...
                         clojure.core/load-libs           core.clj: 5969
                         clojure.core/load-libs           core.clj: 5989
                             clojure.core/apply           core.clj:  667
                                            ...
                          clojure.core/load-lib           core.clj: 5928
                          clojure.core/load-lib           core.clj: 5947
                       clojure.core/load-lib/fn           core.clj: 5948
                          clojure.core/load-one           core.clj: 5908
                                            ...
                              clojure.core/load           core.clj: 6109
                              clojure.core/load           core.clj: 6125
                           clojure.core/load/fn           core.clj: 6126
                                            ...
                        java.lang.Class.forName         Class.java:  427
                       java.lang.Class.forName0          Class.java
                       cljfx.api__init.<clinit>
                           cljfx.api__init.load                   :   70
                                   cljfx.api/fn            api.clj:   83
                      cljfx.platform/initialize       platform.clj:   30
                  cljfx.jdk.platform/initialize       platform.clj:    6
            javafx.application.Platform.startup      Platform.java:  103
com.sun.javafx.application.PlatformImpl.startup  PlatformImpl.java:  267
           com.sun.javafx.tk.Toolkit.getToolkit       Toolkit.java:  272
           java.lang.RuntimeException: No toolkit found
java.lang.ExceptionInInitializerError:

2020-10-19 00:32:24.655 layday ERROR [strongbox.main:26] - Uncaught exception on Thread-0
    java.lang.Thread.run  Thread.java:  832
                     ...
     strongbox.main/stop     main.clj:   69
      strongbox.main/jfx     main.clj:   57
                     ...
    clojure.core/require     core.clj: 6007 (repeats 2 times)
      clojure.core/apply     core.clj:  667
                     ...
  clojure.core/load-libs     core.clj: 5969
  clojure.core/load-libs     core.clj: 5985
      clojure.core/apply     core.clj:  667
                     ...
   clojure.core/load-lib     core.clj: 5928
   clojure.core/load-lib     core.clj: 5947
clojure.core/load-lib/fn     core.clj: 5948
   clojure.core/load-one     core.clj: 5908
                     ...
       clojure.core/load     core.clj: 6109
       clojure.core/load     core.clj: 6125
    clojure.core/load/fn     core.clj: 6126
                     ...
 java.lang.Class.forName   Class.java:  427
java.lang.Class.forName0    Class.java
java.lang.NoClassDefFoundError: Could not initialize class strongbox.ui.jfx__init
```

**Comment by Fred-IV** [comment]
Same issue for me. 2.0.1 works fine, 3.0 is dead.

**Comment by torkus** [comment]
thanks @layday , 

> Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer

this typically means JavaFX is not present, but it *should* have been bundled into the `.jar` file.

> Same issue for me. 2.0.1 works fine, 3.0 is dead.

Fred, does this work for you on 3.0:

    java -jar path/to/strongbox.jar --ui gui1

? or does that fail in a similar way?

**Comment by layday** [comment]
I believe it is bundled with the JAR, just not in a way that is compatible with macOS.  When I run the JAR I built it extracts `libprism_es2.dylib` to `~/.openjfx/cache/14` and loads it.

**Comment by torkus** [comment]
I've uploaded a file to this release built for Java 11:

* https://github.com/ogri-la/strongbox/releases/download/3.0.0/strongbox-3.0.0-standalone-jre11.jar
* https://github.com/ogri-la/strongbox/releases/download/3.0.0/strongbox-3.0.0-standalone-jre11.jar.sha256

**Comment by layday** [comment]
Is it possible to create 'universal' JARs for openjfx?  If not are you able to cross-compile JARs or bundle assets for a different platform?  Otherwise you might be able to set up a separate task on Travis to run on `osx`? I'm not really familiar with the ecosystem, just spitballing.

**Comment by torkus** [comment]
Yes, that's what I'm investigating right now.

**Comment by torkus** [comment]
Alright, would the mac users like to try this download please and let me know if it works?

https://github.com/ogri-la/strongbox/releases/download/macfix/strongbox-3.1.0-unreleased-standalone.jar

**Comment by layday** [comment]
I have done so and it works.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Fred-IV** [comment]
that works.
I tried to double-click it again, after it worked from the terminal with
your method, and it failed again.
Is there a way to edit the jar and start it with those parameters?
For now, I will just make a terminal command on the desktop to do it.
Thanks!
Nice to have it back. I started playing with the other projects to see if
there was a replacement, and instawow works, but yours is so much better.
Please keep up the Mac support!

**Comment by layday** [comment]
> instawow works, but yours is so much better

😭

**Comment by Fred-IV** [comment]
Sorry, it's just that instawow doesn't seem to detect a lot of updates.
I think Strongbox uses more repositories.
instawow will show everything being up to date, then strongbox will show 9
updates.
Also, I was having problems with instawow replacing modified addons.
I had to modify 3 addons to get them to work with Shadowlands, then
instawow goes and downgrades them. It doesn't seem to detect that they have
been modified, where Strongbox doesn't revert them.
It's nice to have options though, and hopefully over time, this mess will
get better since the Twitch feiasco.
The biggest problem with Strongbox is not being Mac native, so there are
pluses and minuses with both.

I appreciate the developers. Keep up the good work.

**Comment by layday** [comment]
> Sorry, it's just that instawow doesn't seem to detect a lot of updates.
I think Strongbox uses more repositories.
instawow will show everything being up to date, then strongbox will show 9
updates.

That would happen because they're not in sync.  instawow won't know if you've modified your add-ons with strongbox and strongbox won't know if you've modified them with instawow.  When you reconcile your add-ons, instawow will reinstall them so you will have the latest version available.  The same happens with strongbox.  Neither manager is able to detect when add-ons have been modified - though you can pin (insawow) or ignore them (strongbox) or choose not to reconcile them.  strongbox and instawow are quite similar in the way they operate.  Either way, thanks for giving instawow a try.

**Comment by seathasky** [comment]
Nice thing about wowup.io is it's like twitch in the fact that it has those
advanced features of just recognizing your add-ons no matter what + no
bloat like twitch, if you can't get strongbox working,I 'd check out their
github, they have a beta version there for mac.

**Comment by Fred-IV** [comment]
I tried. I reconciled, and even after that, it seemed to revert my modified
addons.
Also, detecting the updates was an issue. Again, after the reconcile. I
tried again, and the reconcile list was blank. It seemed to be complete, or
wasn't detecting that there were any more to do.
But, Strongbox didn't behave this way.
I can play with them some more later, and see.
Thanks

**Comment by layday** [comment]
Reconciliation in instawow means, take this add-on folder, find which add-on it belongs to and manage it with instawow. instawow does not detect when changes are made to the contents of the folder - it operates like a pacman - if you do not want to have an add-on be managed by instawow you should not reconcile or install it with instawow. strongbox did not exhibit the same behaviour because you have not recently reconciled your add-ons with strongbox. If you want to opt out of updates of add-ons you have been managing with strongbox you should ignore them (right click, 'Ignore').

Best,

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Fred-IV** [comment]
Thanks. I really like the fast responses and great support.

I will continue to learn them, and test.

Another weird thing I forgot to mention is that Strongbox always wants to
"upgrade" my Buttonforge from "0.9.60" to "0.9.50". Maybe it's a reconcile
thing, and it's completely ignoring the version numbers.

**Comment by Fred-IV** [comment]
Strongbox seems to work well with other updates though.
For example, both apps were showing there was an update for Prat 3.0, so I
updated it in instawow, and refreshed strongbox, and it detected the update
fine.

**Comment by layday** [comment]
> Strongbox seems to work well with other updates though.
For example, both apps were showing there was an update for Prat 3.0, so I
updated it in instawow, and refreshed strongbox, and it detected the update
fine.

I believe strongbox (and @torkus will correct me) will skip updates when the `Title` and `Version` from the TOC file match the name and version from source exactly.  instawow does not have a similar facility.

**Comment by layday** [comment]
By the way, if you've lost your custom edits during reconciliation (for which I am sorry) you might be able to recover them.  instawow does not delete anything outright - it moves add-ons to a temporary folder which is cleaned up on reboot.  From the Terminal, run:

```
open $TMPDIR/instawow
```

**Comment by torkus** [comment]
> Another weird thing I forgot to mention is that Strongbox always wants to
"upgrade" my Buttonforge from "0.9.60" to "0.9.50". Maybe it's a reconcile
thing, and it's completely ignoring the version numbers.

> I believe strongbox (and @torkus will correct me) will skip updates when the Title and Version from the TOC file match the name and version from source exactly.

It's even simpler than that. Strongbox works by comparing just the `version` values and if they are different will prompt you to upgrade. The first version value comes from the `.toc` file, the other version value comes from visiting the addon online after it's been found in the catalogue. 

So if you have instawow installing `Buttonforge` to `0.9.60` (somehow) and then strongbox comes along and compares the latest version available to what is installed:

![Screenshot at 2020-10-20 09-53-11](https://user-images.githubusercontent.com/48790775/96522110-3eb1f880-12ba-11eb-8175-db7a6f1231fc.png)

It's going to say "the latest version available doesn't match what you have installed" and then flag it as upgradeable.

It could be Buttonforge was installed by a different addon manager from a source other than curseforge, like wowinterface or even github. It could be you installed an alpha or beta version of the addon - strongbox ignores unstable or alternate releases.

**Comment by torkus** [comment]
> I tried to double-click it again, after it worked from the terminal with
your method, and it failed again.
Is there a way to edit the jar and start it with those parameters?
For now, I will just make a terminal command on the desktop to do it.

@layday may have some insight here, but is `java` set as the default handler for `.jar` files?

> For now, I will just make a terminal command on the desktop to do it.

Is a 'terminal command' like a bash script? If not and you want a clickable thing that launches strongbox you put this in a file:

```
#!/bin/bash
java -jar /path/to/strongbox.jar
```

make it executable with `chmod +x filename` (or modify it's properties or whatever) and that should work.

**Comment by layday** [comment]
Yes, Java is the default handler - wouble-clicking on a JAR file will open it with Java.  I believe they were using 3.0.0 with the `--ui gui1` option, they are not able to open it because it defaults to the new UI.

**Comment by torkus** [comment]
fixed in 3.0.1, thanks for your patience everyone 

(everyone except ***seathasky*** that is)

**Comment by seathasky** [comment]
Haha. I'm still here. ;)

**Comment by seathasky** [comment]
Testing now, and working great! Thanks @torkus

**Comment by promisedlandt** [comment]
I still have this issue on Linux. Should I open a new issue?

**Comment by torkus** [comment]
@promisedlandt , please do. Include the version of java you're using and the complete error you're seeing

**Comment by promisedlandt** [comment]
> @promisedlandt , please do. Include the version of java you're using and the complete error you're seeing

False alarm, it works fine with the full version, and I probably have an old version of Java.

**Comment by torkus** [comment]
it's being built under java 14 but has been running under java 11 without a problem (for me). I'll drop the build environment to java 11 for the next release just in case.
